//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 10:38:53 PM IST 
//


package com.waruna.gadgetmart_web;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.waruna.gadgetmart_web package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.waruna.gadgetmart_web
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link GetUserOrdersResponse }
     * 
     */
    public GetUserOrdersResponse createGetUserOrdersResponse() {
        return new GetUserOrdersResponse();
    }

    /**
     * Create an instance of {@link OrderItem }
     * 
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

    /**
     * Create an instance of {@link GetInventoryResponse }
     * 
     */
    public GetInventoryResponse createGetInventoryResponse() {
        return new GetInventoryResponse();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link SaveOrderRequest }
     * 
     */
    public SaveOrderRequest createSaveOrderRequest() {
        return new SaveOrderRequest();
    }

    /**
     * Create an instance of {@link SaveUserRequest }
     * 
     */
    public SaveUserRequest createSaveUserRequest() {
        return new SaveUserRequest();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link SaveVendorRequest }
     * 
     */
    public SaveVendorRequest createSaveVendorRequest() {
        return new SaveVendorRequest();
    }

    /**
     * Create an instance of {@link GetVendorResponse }
     * 
     */
    public GetVendorResponse createGetVendorResponse() {
        return new GetVendorResponse();
    }

    /**
     * Create an instance of {@link SaveOrderResponse }
     * 
     */
    public SaveOrderResponse createSaveOrderResponse() {
        return new SaveOrderResponse();
    }

    /**
     * Create an instance of {@link SaveVendorResponse }
     * 
     */
    public SaveVendorResponse createSaveVendorResponse() {
        return new SaveVendorResponse();
    }

    /**
     * Create an instance of {@link GetInventoryRequest }
     * 
     */
    public GetInventoryRequest createGetInventoryRequest() {
        return new GetInventoryRequest();
    }

    /**
     * Create an instance of {@link UpdateVendorResponse }
     * 
     */
    public UpdateVendorResponse createUpdateVendorResponse() {
        return new UpdateVendorResponse();
    }

    /**
     * Create an instance of {@link GetVendorRequest }
     * 
     */
    public GetVendorRequest createGetVendorRequest() {
        return new GetVendorRequest();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateVendorRequest }
     * 
     */
    public UpdateVendorRequest createUpdateVendorRequest() {
        return new UpdateVendorRequest();
    }

    /**
     * Create an instance of {@link SaveUserResponse }
     * 
     */
    public SaveUserResponse createSaveUserResponse() {
        return new SaveUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link GetUserOrdersRequest }
     * 
     */
    public GetUserOrdersRequest createGetUserOrdersRequest() {
        return new GetUserOrdersRequest();
    }

}
